---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: jackett-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :9117
    curl_opts: -c /dev/null
    repo: jackett-dev

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: jackett-dev
    repo: spritsail/jackett
    tags:
    - latest
    - "%label io.spritsail.version.jackett"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 006e85e500f27e48f470c51eec97888b87a2ab1f7f213a6b97489ff96ed2e75f

...
