---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: jackett-dotnet-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :9117
    curl_opts: -c /dev/null
    repo: jackett-dotnet-dev

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: jackett-dotnet-dev
    repo: spritsail/jackett
    tags:
    - dotnet
    - '%label io.spritsail.version.jackett | %prefix dotnet'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - dotnet
    event:
    - push

---
kind: signature
hmac: 00146c6b1e658c5df6616d41c81c02b380ebd8e027da639cce9402cef8d826fb

...
