pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: jackett-dotnet-dev


  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: jackett-dotnet-dev
    curl: ':9117'
    curl_opts: '-c /dev/null'

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ dotnet ], event: [ push, tag, deployment ] }
    from: jackett-dotnet-dev
    repo: spritsail/jackett
    tags:
      - 'dotnet'
      - '%label io.spritsail.version.jackett | %prefix dotnet'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
